version: "3"

services:
  db:
    build: "./UMAMI-db"
    ports:
      - "3366:3306"
    volumes:
      - ./UMAMI-db/conf.d:/etc/mysql/conf.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=UMAMI
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@123
      - MYSQL_ROOT_PASSWORD=root@123
    container_name: UMAMI-db

  db-test:
    image: mysql:8.0
    ports:
      - "3367:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=UMAMI
      - MYSQL_PORT=3306
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@123
      - MYSQL_ROOT_PASSWORD=root@123
    container_name: UMAMI-db-test
