server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3366/UMAMI?useUnicode=true&characterEncoding=utf8mb4
    username: admin
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
